name: Build and Deploy

# 当向 dev 分支推送代码（或定时拉取更新到 dev 分支）时触发部署
on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build-and-deploy:
    # 增加一道安全防线：确保只有你自己的 GitHub 账号运行该工作流时才真正执行部署
    if: github.repository_owner == 'DearXuan7392'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0' # 选择适合的 Node.js 版本
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build
      
      - name: Deploy to EdgeOne Pages
        # 将项目名称和令牌全部替换为了通过全局 Secrets 动态读取
        run: npx edgeone pages deploy ./src/main/webapp -n ${{ secrets.EDGEONE_PROJECT_NAME }} -t ${{ secrets.EDGEONE_API_TOKEN }}
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
          EDGEONE_PROJECT_NAME: ${{ secrets.EDGEONE_PROJECT_NAME }}
